name: Validate HACS

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: "integration"
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: home-assistant/actions/hassfest@master
